=== niladri-basu/bss-brm/bss-brm/brmapp/ifw/tools/XmlLoader/CustomConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="VARCHAR_4000">
		<xs:restriction base="xs:string">
			<xs:maxLength value="256"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ConstraintType">
		<xs:attribute name="RegExFields" type="VARCHAR_4000"/>
		<xs:attribute name="AddDependingTable" type="VARCHAR_4000"/>
		<xs:attribute name="AddDependingTableMapping" type="VARCHAR_4000"/>
		<xs:attribute name="DependingTableNames" type="VARCHAR_4000"/>
	</xs:complexType>
	<xs:element name="IFW">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="IFW_AGGREGATION" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_ALIAS_MAP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_APN_GROUP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_APN_MAP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_CALENDAR" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_CIBER_OCC" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_CLASS" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_CLASSCON" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_CLASSCON_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_CLASSITEM" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_CLASS_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_CONDITION" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_CURRENCY" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DAYCODE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DBVERSION" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DESTINDESC" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DICTIONARY" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DISCARDING" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DISCOUNTDETAIL" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DISCOUNTMASTER" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DISCOUNTMODEL" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DISCOUNTRULE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DISCOUNTSTEP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DSCBALIMPACT" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DSCCONDITION" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DSCMDL_CNF" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DSCMDL_VER" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_DSCTRIGGER" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_EDRC_DESC" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_EDRC_FIELD" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_EXCHANGE_RATE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_GEOAREA_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_GEO_MODEL" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_GEO_ZONE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_GLACCOUNT" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_GROUPING" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_GROUPING_CNF" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_HOLIDAY" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_ICPRODUCT" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_ICPRODUCT_CNF" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_ICPRODUCT_GRP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_ICPRODUCT_RATE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_IMPACT_CAT" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_ISCRIPT" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_MAP_GROUP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_MODEL_SELECTOR" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_NETWORKMODEL" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_NETWORKOPER" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_NOPRODUCT" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_NOPRODUCT_CNF" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_NOSP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_NO_BILLRUN" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_PIPELINE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_POI" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_POIAREA_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_PRICEMDL_STEP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_PRICEMODEL" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_QUEUE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RATEADJUST" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RATEPLAN" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RATEPLAN_CNF" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RATEPLAN_VER" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_REF_MAP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RESOURCE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_REVENUEGROUP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RSC_GROUP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RSC_MAP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RULE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RULEITEM" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RULESET" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RULESETLIST" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RUM" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RUMGROUP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_RUMGROUP_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SCENARIO" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SEGMENT" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SEGRATE_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SEGZONE_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SELECTOR_BLOCK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SELECTOR_BLOCK_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SELECTOR_DETAIL" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SELECTOR_RULE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SELECTOR_RULESET" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SELECTOR_RULE_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SEQCHECK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SEQLOG_IN" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SEQLOG_OUT" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SERVICE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SERVICECLASS" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SERVICE_MAP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SLA" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SOCIALNUMBER" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SPECIALDAYRATE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SPECIALDAY_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SPLITTING_TYPE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_STANDARD_ZONE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SWITCH" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SYNC" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_SYSTEM_BRAND" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_TAX" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_TAXCODE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_TAXGROUP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_TIMEINTERVAL" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_TIMEMODEL" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_TIMEMODEL_LNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_TIMEZONE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_TRUNK" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_TRUNK_CNF" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_UOM" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_UOM_MAP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_USAGECLASS" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_USAGECLASS_MAP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_USAGETYPE" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_USC_GROUP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_USC_MAP" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="IFW_ZONEMODEL" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== niladri-basu/bss-brm/bss-brm/brmapp/ifw/tools/XmlLoader/CustomConfigMigration.xml
<?xml version="1.0" encoding="UTF-8"?>
<IFW xsi:noNamespaceSchemaLocation="CustomConfig.xsd"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <IFW_RATEPLAN RegExFields="CODE|NAME"/>
  <IFW_ALIAS_MAP AddDependingTable="IFW_EDRC_DESC"
                 AddDependingTableMapping="EDRC_DESC:EDRC_DESC"/>
  <IFW_ALIAS_MAP AddDependingTable="IFW_EDRC_FIELD"
                 AddDependingTableMapping="FIELD_ID:FIELD_ID"/>
  <IFW_APN_MAP AddDependingTable="IFW_APN_GROUP"
               AddDependingTableMapping="APN_GROUP:APN_GROUP"/>
  <IFW_CIBER_OCC AddDependingTable="IFW_NETWORKOPER"
                 AddDependingTableMapping="NO:NO"/>
  <IFW_DICTIONARY AddDependingTable="IFW_QUEUE"
                  AddDependingTableMapping="IMPORT_TABLE:IMPORT_TABLE"/>
  <IFW_DISCARDING AddDependingTable="IFW_PIPELINE"
                  AddDependingTableMapping="PIPELINE:PIPELINE"/>
  <!--IFW_DISCOUNTDETAIL AddDependingTable="IFW_DISCOUNTMASTER"
                      AddDependingTableMapping="DISCOUNTMASTER:DISCOUNTMASTER"/>
  <IFW_DISCOUNTSTEP AddDependingTable="IFW_DISCOUNTRULE"
                    AddDependingTableMapping="DISCOUNTRULE:DISCOUNTRULE"/>
  <IFW_DSCMDL_VER AddDependingTable="IFW_DISCOUNTMODEL"
                  AddDependingTableMapping="DISCOUNTMODEL:DISCOUNTMODEL"/-->
  <IFW_EDRC_FIELD AddDependingTable="IFW_EDRC_DESC"
                  AddDependingTableMapping="EDRC_DESC:EDRC_DESC"/>
  <IFW_EXCHANGE_RATE AddDependingTable="IFW_CURRENCY"
                     AddDependingTableMapping="FROM_CURRENCY:CURRENCY"/>
  <IFW_EXCHANGE_RATE AddDependingTable="IFW_CURRENCY"
                     AddDependingTableMapping="TO_CURRENCY:CURRENCY"/>
  <IFW_GEO_MODEL AddDependingTable="IFW_RULESET"
                 AddDependingTableMapping="RULESET:RULESET"/>
  <IFW_GEO_ZONE AddDependingTable="IFW_IMPACT_CAT"
                AddDependingTableMapping="ZONE_RT:IMPACT_CATEGORY"/>
  <IFW_GEO_ZONE AddDependingTable="IFW_IMPACT_CAT"
                AddDependingTableMapping="ZONE_WS:IMPACT_CATEGORY"/>
  <IFW_GEO_ZONE AddDependingTable="IFW_SERVICE"
                AddDependingTableMapping="SERVICECODE:SERVICECODE"/>
  <IFW_GEO_ZONE AddDependingTable="IFW_ZONEMODEL"
                AddDependingTableMapping="ALT_ZONEMODEL:ZONEMODEL"/>
  <IFW_GEO_ZONE AddDependingTable="IFW_ZONEMODEL"
                AddDependingTableMapping="ZONEMODEL:ZONEMODEL"/>
  <IFW_GEOAREA_LNK AddDependingTable="IFW_GEO_MODEL"
                   AddDependingTableMapping="GEOMODEL:GEOMODEL"/>
  <IFW_GLACCOUNT AddDependingTable="IFW_TAXCODE"
                 AddDependingTableMapping="TAXCODE:TAXCODE"/>
  <IFW_GROUPING AddDependingTable="IFW_EDRC_FIELD"
                AddDependingTableMapping="FIELD_ID:FIELD_ID"/>
  <IFW_GROUPING AddDependingTable="IFW_SCENARIO"
                AddDependingTableMapping="SCENARIO_ID:SCENARIO_ID"/>
  <IFW_HOLIDAY AddDependingTable="IFW_CALENDAR"
               AddDependingTableMapping="CALENDAR:CALENDAR"/>
  <IFW_ICPRODUCT_CNF AddDependingTable="IFW_ICPRODUCT"
                     AddDependingTableMapping="ICPRODUCT:ICPRODUCT"/>
  <IFW_ICPRODUCT_CNF AddDependingTable="IFW_ICPRODUCT_GRP"
                     AddDependingTableMapping="ICPRODUCT_GROUP:ICPRODUCT_GROUP"/>
  <IFW_ICPRODUCT_CNF AddDependingTable="IFW_NETWORKMODEL"
                     AddDependingTableMapping="NETWORKMODEL:NETWORKMODEL"/>
  <IFW_ICPRODUCT_GRP AddDependingTable="IFW_NETWORKMODEL"
                     AddDependingTableMapping="NETWORKMODEL:NETWORKMODEL"/>
  <IFW_ICPRODUCT_RATE AddDependingTable="IFW_ICPRODUCT"
                      AddDependingTableMapping="ICPRODUCT:ICPRODUCT"/>
  <IFW_ICPRODUCT_RATE AddDependingTable="IFW_NETWORKMODEL"
                      AddDependingTableMapping="NETWORKMODEL:NETWORKMODEL"/>
  <IFW_ICPRODUCT_RATE AddDependingTable="IFW_NETWORKOPER"
                      AddDependingTableMapping="NO:NO"/>
  <IFW_ICPRODUCT_RATE AddDependingTable="IFW_RATEPLAN"
                      AddDependingTableMapping="ALT_RATEPLAN:RATEPLAN"/>
  <IFW_ICPRODUCT_RATE AddDependingTable="IFW_RATEPLAN"
                      AddDependingTableMapping="RATEPLAN:RATEPLAN"/>
  <IFW_NETWORKMODEL AddDependingTable="IFW_CURRENCY"
                    AddDependingTableMapping="CURRENCY:CURRENCY"/>
  <IFW_NETWORKMODEL AddDependingTable="IFW_NETWORKOPER"
                    AddDependingTableMapping="NO:NO"/>
  <IFW_NETWORKMODEL AddDependingTable="IFW_RATEPLAN"
                    AddDependingTableMapping="RATEPLAN:RATEPLAN"/>
  <IFW_NETWORKMODEL AddDependingTable="IFW_SYSTEM_BRAND"
                    AddDependingTableMapping="SYSTEM_BRAND:SYSTEM_BRAND"/>
  <IFW_NETWORKOPER AddDependingTable="IFW_CURRENCY"
                   AddDependingTableMapping="CURRENCY:CURRENCY"/>
  <IFW_NETWORKOPER AddDependingTable="IFW_TAXGROUP"
                   AddDependingTableMapping="TAXGROUP:TAXGROUP"/>
  <IFW_NO_BILLRUN AddDependingTable="IFW_NETWORKMODEL"
                  AddDependingTableMapping="NETWORKMODEL:NETWORKMODEL"/>
  <IFW_NO_BILLRUN AddDependingTable="IFW_NETWORKOPER"
                  AddDependingTableMapping="NO:NO"/>
  <IFW_NOPRODUCT AddDependingTable="IFW_CURRENCY"
                 AddDependingTableMapping="CURRENCY:CURRENCY"/>
  <IFW_NOPRODUCT AddDependingTable="IFW_NETWORKOPER"
                 AddDependingTableMapping="NO:NO"/>
  <IFW_NOPRODUCT_CNF AddDependingTable="IFW_ICPRODUCT"
                     AddDependingTableMapping="ICPRODUCT:ICPRODUCT"/>
  <IFW_NOPRODUCT_CNF AddDependingTable="IFW_IMPACT_CAT"
                     AddDependingTableMapping="IMPACT_CATEGORY:IMPACT_CATEGORY"/>
  <IFW_NOPRODUCT_CNF AddDependingTable="IFW_NETWORKOPER"
                     AddDependingTableMapping="NO:NO"/>
  <IFW_NOPRODUCT_CNF AddDependingTable="IFW_NOPRODUCT"
                     AddDependingTableMapping="PRODUCTCODE:PRODUCTCODE"/>
  <IFW_NOPRODUCT_CNF AddDependingTable="IFW_TIMEZONE"
                     AddDependingTableMapping="TIMEZONE:TIMEZONE"/>
  <IFW_NOSP AddDependingTable="IFW_MAP_GROUP"
            AddDependingTableMapping="MAP_GROUP:MAP_GROUP"/>
  <IFW_PIPELINE AddDependingTable="IFW_EDRC_DESC"
                AddDependingTableMapping="EDRC_DESC:EDRC_DESC"/>
  <IFW_POIAREA_LNK AddDependingTable="IFW_NETWORKMODEL"
                   AddDependingTableMapping="NETWORKMODEL:NETWORKMODEL"/>
  <IFW_POIAREA_LNK AddDependingTable="IFW_POI"
                   AddDependingTableMapping="POI:POI"/>
  <IFW_PRICEMODEL AddDependingTable="IFW_PRICEMDL_STEP"
                  AddDependingTableMapping="PRICEMODEL:PRICEMODEL"/>
  <IFW_RATEADJUST AddDependingTable="IFW_RATEPLAN"
                  AddDependingTableMapping="RATEPLAN:RATEPLAN"/>
  <IFW_RATEADJUST AddDependingTable="IFW_RATEPLAN_VER"
                  AddDependingTableMapping="RATEPLAN:RATEPLAN"/>
  <IFW_RATEPLAN AddDependingTable="IFW_RATEPLAN_VER"
                AddDependingTableMapping="RATEPLAN:RATEPLAN"/>
  <IFW_RATEPLAN AddDependingTable="IFW_RATEPLAN_CNF"
                AddDependingTableMapping="RATEPLAN:RATEPLAN"/>
  <IFW_RATEPLAN AddDependingTable="IFW_RATEADJUST"
                AddDependingTableMapping="RATEPLAN:RATEPLAN"/>
  <IFW_RATEPLAN AddDependingTable="IFW_SPECIALDAY_LNK"
                AddDependingTableMapping="RATEPLAN:RATEPLAN"/>
  <IFW_RATEPLAN_CNF DependingTableNames="IFW_RATEPLAN_VER|IFW_RATEPLAN_CNF"/>
  <IFW_RATEPLAN_CNF DependingTableNames=""/>
  <IFW_RESOURCE AddDependingTable="IFW_CURRENCY"
                AddDependingTableMapping="CURRENCY:CURRENCY"/>
  <IFW_RSC_MAP AddDependingTable="IFW_RSC_GROUP"
               AddDependingTableMapping="RSC_GROUP:RSC_GROUP"/>
  <IFW_RSC_MAP AddDependingTable="IFW_SERVICECLASS"
               AddDependingTableMapping="NEW_SERVICECLASS:SERVICECLASS"/>
  <IFW_RULEITEM AddDependingTable="IFW_RULE"
                AddDependingTableMapping="RULE_ID:RULE_ID"/>
  <IFW_RULESETLIST AddDependingTable="IFW_RULE"
                   AddDependingTableMapping="RULE_ID:RULE_ID"/>
  <IFW_RULESETLIST AddDependingTable="IFW_RULESET"
                   AddDependingTableMapping="RULESET:RULESET"/>
  <IFW_RUMGROUP_LNK AddDependingTable="IFW_RUM"
                    AddDependingTableMapping="RUM:RUM"/>
  <IFW_RUMGROUP_LNK AddDependingTable="IFW_RUMGROUP"
                    AddDependingTableMapping="RUMGROUP:RUMGROUP"/>
  <IFW_RUMGROUP_LNK AddDependingTable="IFW_UOM"
                    AddDependingTableMapping="UOM:UOM"/>
  <IFW_SCENARIO AddDependingTable="IFW_EDRC_DESC"
                AddDependingTableMapping="EDRC_DESC:EDRC_DESC"/>
  <IFW_SEGRATE_LNK AddDependingTable="IFW_RATEPLAN"
                   AddDependingTableMapping="RATEPLAN:RATEPLAN"/>
  <IFW_SEGRATE_LNK AddDependingTable="IFW_SEGMENT"
                   AddDependingTableMapping="SEGMENT:SEGMENT"/>
  <IFW_SEGZONE_LNK AddDependingTable="IFW_SEGMENT"
                   AddDependingTableMapping="SEGMENT:SEGMENT"/>
  <IFW_SEGZONE_LNK AddDependingTable="IFW_ZONEMODEL"
                   AddDependingTableMapping="ZONEMODEL:ZONEMODEL"/>
  <IFW_SELECTOR_BLOCK_LNK AddDependingTable="IFW_SELECTOR_BLOCK"
                          AddDependingTableMapping="SELECTOR_BLOCK:SELECTOR_BLOCK"/>
  <IFW_SELECTOR_BLOCK_LNK AddDependingTable="IFW_SELECTOR_BLOCK"
                          AddDependingTableMapping="SELECTOR_SUB_BLOCK:SELECTOR_BLOCK"/>
  <IFW_SELECTOR_BLOCK_LNK AddDependingTable="IFW_SELECTOR_DETAIL"
                          AddDependingTableMapping="SELECTOR_DETAIL:SELECTOR_DETAIL"/>
  <IFW_SELECTOR_RULE_LNK AddDependingTable="IFW_SELECTOR_BLOCK"
                         AddDependingTableMapping="SELECTOR_BLOCK:SELECTOR_BLOCK"/>
  <!--IFW_SELECTOR_RULE_LNK AddDependingTable="IFW_SELECTOR_DETAIL"
                         AddDependingTableMapping="SELECTOR_DETAIL:SELECTOR_DETAIL"/-->
  <IFW_SELECTOR_RULE_LNK AddDependingTable="IFW_SELECTOR_RULE"
                         AddDependingTableMapping="SELECTOR_RULE:SELECTOR_RULE"/>
  <IFW_SELECTOR_RULESET AddDependingTable="IFW_MODEL_SELECTOR"
                        AddDependingTableMapping="MODEL_SELECTOR:MODEL_SELECTOR"/>
