=== niladri-basu/bss-brm/bss-brm/brmapp/ifw/TD/formatDesc/Formats/Realtime/opcode_ifw_mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="EdrBlock">
		<xs:complexType>
			<xs:attribute name="name" use="required"/>
			<xs:attribute name="use" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="lazyCreate"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="PropagateBlock">
		<xs:complexType>
			<xs:attribute name="name" use="required"/>
			<xs:attribute name="use" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="optional"/>
						<xs:enumeration value="required"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="EdrField">
		<xs:complexType>
			<xs:attribute name="name" use="required"/>
			<xs:attribute name="value" use="optional"/>
			<xs:attribute name="useAlias" use="optional"/>
			<xs:attribute name="useArrayIndex" use="optional"/>
			<xs:attribute name="concat" type="xs:string" use="optional"/>
			<xs:attribute name="format" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="short"/>
						<xs:enumeration value="long"/>
						<xs:enumeration value="id"/>
						<xs:enumeration value="type"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="FlistField">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="EdrBlock"/>
				<xs:element ref="PropagateBlock"/>
				<xs:element ref="EdrField"/>
				<xs:element ref="FlistField"/>
			</xs:choice>
			<xs:attribute name="name" use="required"/>
			<xs:attribute name="use" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="optional"/>
						<xs:enumeration value="required"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="format" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="short"/>
						<xs:enumeration value="long"/>
						<xs:enumeration value="id"/>
						<xs:enumeration value="type"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="applyUTCOffset" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="target"/>
			<xs:attribute name="alias" type="xs:string"/>
			<xs:attribute name="onAlias" type="xs:string"/>
			<xs:attribute name="onAliasValue" type="xs:string"/>
			<xs:attribute name="concat" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="InputMap">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="EdrBlock"/>
				<xs:element ref="PropagateBlock"/>
				<xs:element ref="EdrField"/>
				<xs:element ref="FlistField"/>
			</xs:choice>
			<xs:attribute name="containerType" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="OutputMap"/>
	<xs:element name="OpcodeMap">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="1">
				<xs:element ref="InputMap"/>
				<xs:element ref="OutputMap"/>
			</xs:choice>
			<xs:attribute name="opName" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== niladri-basu/bss-brm/bss-brm/brmapp/ifw/formatDesc/Formats/Realtime/zonemap_event.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--Module Version : 10000-->
<OpcodeMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./opcode_ifw_mapping.xsd" opName="PCM_OP_RATE_GET_ZONEMAP_INFO">
<!--@(#)%Portal Version: zonemap_event.xml:Pipeline7.3PatchInt:2:2006-Dec-15 11:56:14 %-->
	<InputMap containerType="DETAIL">
		<!--CONSTANT EDR DETAIL ITEMS-->
		<EdrField name="DETAIL.RECORD_TYPE" value="020"/>
		<EdrField name="DETAIL.DISCARDING" value="0"/>
		<!--EVENT FLIST STRUCT ITEM-->
		<FlistField name="PIN_FLD_EVENT">
			<!--EVENT_TYPE-->
			<FlistField name="PIN_FLD_POID" format="type" target="DETAIL.EVENT_TYPE" alias="event_type"/>
			<!--CHARGING_START-->
			<FlistField name="PIN_FLD_START_T" target="DETAIL.CHARGING_START_TIMESTAMP" applyUTCOffset="true" use="optional"/>
			<!--CHARGING_END-->
			<FlistField name="PIN_FLD_END_T" target="DETAIL.CHARGING_END_TIMESTAMP" applyUTCOffset="true" use="optional"/>
		</FlistField>
		<!--END EVENT FLIST STRUCT ITEM-->
		<!--SERVICE_CODE-->
		<FlistField name="PIN_FLD_SERVICE_CLASS" format="short" target="DETAIL.INTERN_SERVICE_CODE" use="optional"/>
                <!--A_NUMBER and B_NUMBER-->
		<FlistField name="PIN_FLD_ANI" target="DETAIL.INTERN_A_NUMBER_ZONE" use="optional"/>
		<FlistField name="PIN_FLD_DN" target="DETAIL.INTERN_B_NUMBER_ZONE" use="optional"/>
                <!--ZONE_MAP_NAME--> 
		<FlistField name="PIN_FLD_ZONEMAP_NAME" target="DETAIL.ZONE_ENTRY_NAME"/>
	</InputMap>
</OpcodeMap>
